name: AdvEnum
description: A starting point for Dart libraries or applications.
version: 1.0.0
author: fakhar <fakharamirali@gmail.com>
homepage: https://github.com/fakharamirali/AdvEnum

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.0.0

repository: https://github.com/fakharamirali/AdvEnum